### ISSUE TITLE
Dependabot does not reliably create base image updates due to missing auth

### ISSUE THREAD

**Issue by hairmare** [adfinis/openshift-etcd-backup#38]
The registry.access.redhat.com registry has rate-limiting which is why dependabot can't reliably update the image as needed.

## proposed solution

Use [updatecli](https://www.updatecli.io/) to update the base image `FROM` based on an API to redhat's high order API and not the OCI registries API. An example of how this can work is in [radiorabe/container-image-ubi8-minimal](https://github.com/radiorabe/container-image-ubi8-minimal), the example is like 80% the way there and i expect there to be some copypasta from there soon.

## other solutions

figure out to to provide dependabot with a dedicated registry token so we don't run into rate-limiting.

**Comment by tongpu** [comment]
Did we actively resolve this issue or did it somehow resolve on its own?

**Comment by hairmare** [comment]
we did not solve this. Sometimes dependabot gets lucky and creates a PR before getting rate-limited by the redhat registry again

**Comment by tongpu** [comment]
Is the implementation in [radiorabe/container-image-ubi8-minimal](https://github.com/radiorabe/container-image-ubi8-minimal) ready to also be implemented here?

**Comment by hairmare** [comment]
> Is the implementation in [radiorabe/container-image-ubi8-minimal](https://github.com/radiorabe/container-image-ubi8-minimal) ready to also be implemented here?

afaict we didn't need it anymore once redhat switched to hosting their images from quay rather than their previous solution

we also ended up switching to almalinux for consistency and [radiorabe/container-image-ubi9-minimal](https://github.com/radiorabe/container-image-ubi9-minimal) is our primary focus now as well (hence i never removed updatecli from ubi8).

**Comment by hairmare** [comment]
it looks like this has been mitigated since Red Hat migrated their repo to quay.io :mechanical_arm:
