### ISSUE TITLE
Switch base image to ubi9-minimal

### ISSUE THREAD

**Issue by tongpu** [adfinis/openshift-etcd-backup#67]
Starting with OpenShift 4.13 the RHCOS version used for nodes will be based on RHEL 9.2 ([see here](https://access.redhat.com/articles/6907891)), so we should probably switch the build process to use `FROM ubi9-minimal`.

Are there any objections from anyone for that change? @vmaillot @paraenggu @eyenx @hairmare

**Comment by eyenx** [comment]
None.

**Comment by vmaillot** [comment]
fine for me as well, let's test it during the next openshift maintenance, thanks!
