### ISSUE TITLE
ERROR: Can't start the cronjob on Kubernetes through the Helm chart.

### ISSUE THREAD

**Issue by Federico-Baldan** [adfinis/openshift-etcd-backup#95]
Hi , when i deploy through the helm chart it gave me this error...

```
Added `etcd-backup` successfully.
+ bash -o history
++ date +etcd-backup-%FT%T%:z
+ BACKUP_FOLDER=etcd-backup-2024-10-07T14:33:55+00:00
+ mkdir -p /host/var/tmp/etcd-backup/etcd-backup-2024-10-07T14:33:55+00:00
+ chroot /host /usr/local/bin/cluster-backup.sh /var/tmp/etcd-backup/etcd-backup-2024-10-07T14:33:55+00:00
chroot: failed to run command '/usr/local/bin/cluster-backup.sh': No such file or directory
```

i use the standard values.yaml but i change only the value of the S3 bucket.

Could you please help me?
ty in advance

**Comment by tongpu** [comment]
This repo and the commands are specific to OpenShift and won't work in a normal Kubernetes environment. For Kubernetes we have [kubernetes-etcd-backup](https://github.com/adfinis/kubernetes-etcd-backup)
